### PR TITLE
Update dev instructions

### PR DESCRIPTION
**Pull request by ianhi**
sibling to: https://github.com/jupyterlab/extension-cookiecutter-ts/pull/67
- use `install` instead of `link`
- explain `--watch` mode

### CODE REVIEW

**Comment by blink1073** [comment]
Kicking CI to pick up the change from Travis -> GH Actions.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by ianhi** [comment]
Just noticed that ipympl (which uses js not ts) has `npm run watch` in the instructions https://github.com/matplotlib/ipympl#for-a-development-installation-requires-nodejs

does the js cookiecutter also need this in the instructions? I always assumed that the `jlpm watch` was for compiling the typescript to javascript so I didn't include it in this PR.

**Comment by blink1073** [comment]
Right, no `watch` is needed for this cookiecutter.

**Pull request merged**
