### PR TITLE
Switch to the new extension distribution system

### LINKED ISSUE #32: Adopt the new extension distribution system
The cookiecutter should already be compatible with 3.0, and the extension can be installed with `jupyter labextension install`.

The main question is whether to adopt the new distribution system. It looks like it would make sense to do it so it's similar to the other cookiecutter: https://github.com/jupyterlab/extension-cookiecutter-ts

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #32 

This was bootstrapped from the TypeScript cookiecutter: https://github.com/jupyterlab/extension-cookiecutter-ts

Then:

- removed TypeScript files and TypeScript related scripts
- removed the optional server exension
- added `lib/index.js`

Can be tested locally with:

```bash
mamba create -n test cookiecutter nodejs python  -y
conda activate test
cookiecutter https://github.com/jtpio/extension-cookiecutter-js --checkout packaging
```

### CODE REVIEW

**Comment by jtpio** [comment]
Since quite a bit of the boilerplate code now comes from the TypeScript cookiecutter, it would be nice if the JS cookiecutter could somehow "inherit" from the TS cookiecutter (which is more actively maintained), and only keep the JS relevant parts.

**Comment by jtpio** [comment]
Alternatively, maybe the TS cookiecutter should actually support JS too? When prompted, the extension author could choose between a JS or TS extension (defaulting to TS):

- if JS, then the `lib` folder is created
- if TS, then the `src` folder and other TypeScript related files are populated

Which means the https://github.com/jupyterlab/extension-cookiecutter-js repo could simply be archived in favor of https://github.com/jupyterlab/extension-cookiecutter-ts.

**Comment by blink1073** [comment]
Looks like inheriting cookiecutters is not yet possible: https://github.com/cookiecutter/cookiecutter/pull/1485

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
